services:
  # 1. FastAPI Backend
  - type: web
    name: techgear-backend
    env: python
    rootDir: Backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: samuelpalaciohoyos_db_user

  # 2. Django Frontend
  - type: web
    name: techgear-frontend
    env: python
    rootDir: Frontend
    buildCommand: "./build.sh"
    startCommand: "gunicorn techgear.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: API_URL
        fromService:
          type: web
          name: techgear-backend
          property: host
